import prisma from './prisma'

async function main() {
  console.log('--- PURGING DUMMY / PREVIOUS TEST INVENTORY DATA ---')
  await prisma.inventarioFilamento.deleteMany({})
  await prisma.consumibleTaller.deleteMany({})

  console.log('--- SEEDING REAL WORKSHOP INVENTORY (LISTA MANUAL DE STOCK) ---')

  const filamentos = [
    // 1. ABIERTOS / EN USO
    {
      nombreColor: 'Blanco Hueso',
      codigoHex: '#F5F5F0',
      tipoMaterial: 'PLA Matte',
      marca: 'eSUN',
      formato: 'CON_BOBINA',
      estadoStock: 'ABIERTO',
      porcentajeRestante: 65.0,
      stockBobinas: 0.65,
      stockGramos: 650,
      cantidadCompradaRef: 1,
      costoBobinaRef: 58.00,
      ubicacion: 'Impresora 1 / Rack A',
      temperaturaImpresion: '205-215°C',
      temperaturaCama: '55-60°C',
      estado: 'DISPONIBLE',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'En uso para litofanías y carcasas decorativas',
      activo: true,
    },
    {
      nombreColor: 'Lila Púrpura',
      codigoHex: '#C084FC',
      tipoMaterial: 'PLA+',
      marca: 'Sunlu',
      formato: 'CON_BOBINA',
      estadoStock: 'ABIERTO',
      porcentajeRestante: 40.0,
      stockBobinas: 0.40,
      stockGramos: 400,
      cantidadCompradaRef: 1,
      costoBobinaRef: 56.00,
      ubicacion: 'Impresora 2 / Rack A',
      temperaturaImpresion: '210-220°C',
      temperaturaCama: '60°C',
      estado: 'BAJO_STOCK',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Excelente acabado pastel para figuras y accesorios',
      activo: true,
    },
    {
      nombreColor: 'Rojo Escarlata',
      codigoHex: '#DC2626',
      tipoMaterial: 'PLA',
      marca: 'Creality',
      formato: 'CON_BOBINA',
      estadoStock: 'ABIERTO',
      porcentajeRestante: 80.0,
      stockBobinas: 0.80,
      stockGramos: 800,
      cantidadCompradaRef: 1,
      costoBobinaRef: 55.00,
      ubicacion: 'Rack Principal - Nivel 1',
      temperaturaImpresion: '200-210°C',
      temperaturaCama: '55°C',
      estado: 'DISPONIBLE',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Rojo vibrante de alta resistencia',
      activo: true,
    },
    {
      nombreColor: 'Gris Ceniza',
      codigoHex: '#94A3B8',
      tipoMaterial: 'PLA',
      marca: 'eSUN',
      formato: 'REFILL',
      estadoStock: 'ABIERTO',
      porcentajeRestante: 50.0,
      stockBobinas: 0.50,
      stockGramos: 500,
      cantidadCompradaRef: 1,
      costoBobinaRef: 52.00,
      ubicacion: 'Bobina Reutilizable BR 1',
      temperaturaImpresion: '205-215°C',
      temperaturaCama: '55°C',
      estado: 'DISPONIBLE',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Refill montado en bobina reutilizable',
      activo: true,
    },
    {
      nombreColor: 'Azul Oscuro',
      codigoHex: '#1E3A8A',
      tipoMaterial: 'PLA',
      marca: 'Creality',
      formato: 'CON_BOBINA',
      estadoStock: 'ABIERTO',
      porcentajeRestante: 25.0,
      stockBobinas: 0.25,
      stockGramos: 250,
      cantidadCompradaRef: 1,
      costoBobinaRef: 54.00,
      ubicacion: 'Rack A - Nivel 2',
      temperaturaImpresion: '200-210°C',
      temperaturaCama: '55°C',
      estado: 'BAJO_STOCK',
      alertaCritica: true,
      notaProduccion: 'Supongo que no alcanza para otro pedido',
      notas: 'Queda poco filamento en la bobina',
      activo: true,
    },
    {
      nombreColor: 'Negro Carbón',
      codigoHex: '#18181B',
      tipoMaterial: 'PLA Matte',
      marca: 'eSUN',
      formato: 'CON_BOBINA',
      estadoStock: 'ABIERTO',
      porcentajeRestante: 90.0,
      stockBobinas: 0.90,
      stockGramos: 900,
      cantidadCompradaRef: 1,
      costoBobinaRef: 58.00,
      ubicacion: 'Impresora Principal',
      temperaturaImpresion: '205-215°C',
      temperaturaCama: '60°C',
      estado: 'DISPONIBLE',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Color principal de alta rotación en el taller',
      activo: true,
    },

    // 2. CAJAS SELLADAS / STOCK DE RESERVA
    {
      nombreColor: 'Naranja Mandarina',
      codigoHex: '#F97316',
      tipoMaterial: 'PLA Matte',
      marca: 'eSUN',
      formato: 'CON_BOBINA',
      estadoStock: 'SELLADO',
      porcentajeRestante: 100.0,
      stockBobinas: 1.0,
      stockGramos: 1000,
      cantidadCompradaRef: 1,
      costoBobinaRef: 58.00,
      ubicacion: 'Almacén - Caja 1',
      temperaturaImpresion: '205-215°C',
      temperaturaCama: '60°C',
      estado: 'DISPONIBLE',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Bobina sellada al vacío con desecante',
      activo: true,
    },
    {
      nombreColor: 'Marrón Latte',
      codigoHex: '#854D0E',
      tipoMaterial: 'PLA Matte',
      marca: 'Sunlu',
      formato: 'CON_BOBINA',
      estadoStock: 'SELLADO',
      porcentajeRestante: 100.0,
      stockBobinas: 1.0,
      stockGramos: 1000,
      cantidadCompradaRef: 1,
      costoBobinaRef: 56.00,
      ubicacion: 'Almacén - Caja 1',
      temperaturaImpresion: '200-215°C',
      temperaturaCama: '55°C',
      estado: 'DISPONIBLE',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Tono marrón cálido mate',
      activo: true,
    },
    {
      nombreColor: 'Verde Grass',
      codigoHex: '#22C55E',
      tipoMaterial: 'PLA+',
      marca: 'eSUN',
      formato: 'CON_BOBINA',
      estadoStock: 'SELLADO',
      porcentajeRestante: 100.0,
      stockBobinas: 1.0,
      stockGramos: 1000,
      cantidadCompradaRef: 1,
      costoBobinaRef: 58.00,
      ubicacion: 'Almacén - Caja 2',
      temperaturaImpresion: '205-220°C',
      temperaturaCama: '60°C',
      estado: 'DISPONIBLE',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Verde vivo para piezas botánicas',
      activo: true,
    },
    {
      nombreColor: 'Arena',
      codigoHex: '#D4B996',
      tipoMaterial: 'PLA Matte',
      marca: 'eSUN',
      formato: 'REFILL',
      estadoStock: 'SELLADO',
      porcentajeRestante: 100.0,
      stockBobinas: 1.0,
      stockGramos: 1000,
      cantidadCompradaRef: 1,
      costoBobinaRef: 52.00,
      ubicacion: 'Almacén - Refills',
      temperaturaImpresion: '205-215°C',
      temperaturaCama: '55°C',
      estado: 'DISPONIBLE',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Refill ecológico para montar en bobina reutilizable',
      activo: true,
    },
    {
      nombreColor: 'Negro Carbón',
      codigoHex: '#18181B',
      tipoMaterial: 'PLA Matte',
      marca: 'eSUN',
      formato: 'CON_BOBINA',
      estadoStock: 'SELLADO',
      porcentajeRestante: 100.0,
      stockBobinas: 1.0,
      stockGramos: 1000,
      cantidadCompradaRef: 1,
      costoBobinaRef: 58.00,
      ubicacion: 'Almacén - Caja Principal',
      temperaturaImpresion: '205-215°C',
      temperaturaCama: '60°C',
      estado: 'DISPONIBLE',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Reserva para recambio rápido',
      activo: true,
    },
    {
      nombreColor: 'Blanco Hueso',
      codigoHex: '#F5F5F0',
      tipoMaterial: 'PLA Matte',
      marca: 'eSUN',
      formato: 'CON_BOBINA',
      estadoStock: 'SELLADO',
      porcentajeRestante: 100.0,
      stockBobinas: 1.0,
      stockGramos: 1000,
      cantidadCompradaRef: 1,
      costoBobinaRef: 58.00,
      ubicacion: 'Almacén - Caja Principal',
      temperaturaImpresion: '205-215°C',
      temperaturaCama: '60°C',
      estado: 'DISPONIBLE',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Reserva sellada de alta demanda',
      activo: true,
    },
    {
      nombreColor: 'Rojo Escarlata',
      codigoHex: '#DC2626',
      tipoMaterial: 'PLA',
      marca: 'Creality',
      formato: 'CON_BOBINA',
      estadoStock: 'SELLADO',
      porcentajeRestante: 100.0,
      stockBobinas: 1.0,
      stockGramos: 1000,
      cantidadCompradaRef: 1,
      costoBobinaRef: 55.00,
      ubicacion: 'Almacén - Caja 2',
      temperaturaImpresion: '200-210°C',
      temperaturaCama: '55°C',
      estado: 'DISPONIBLE',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Caja sellada de respaldo',
      activo: true,
    },
    {
      nombreColor: 'Rosa Sakura',
      codigoHex: '#F472B6',
      tipoMaterial: 'PLA Silk',
      marca: 'Sunlu Silk',
      formato: 'CON_BOBINA',
      estadoStock: 'SELLADO',
      porcentajeRestante: 100.0,
      stockBobinas: 1.0,
      stockGramos: 1000,
      cantidadCompradaRef: 1,
      costoBobinaRef: 65.00,
      ubicacion: 'Almacén - Caja Silk',
      temperaturaImpresion: '210-220°C',
      temperaturaCama: '60°C',
      estado: 'DISPONIBLE',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Acabado brillante sedoso para regalos especiales',
      activo: true,
    },
    {
      nombreColor: 'Blanco Marfil',
      codigoHex: '#FFFBEB',
      tipoMaterial: 'PLA+',
      marca: 'eSUN',
      formato: 'CON_BOBINA',
      estadoStock: 'SELLADO',
      porcentajeRestante: 100.0,
      stockBobinas: 1.0,
      stockGramos: 1000,
      cantidadCompradaRef: 1,
      costoBobinaRef: 58.00,
      ubicacion: 'Almacén - Caja 1',
      temperaturaImpresion: '205-215°C',
      temperaturaCama: '60°C',
      estado: 'DISPONIBLE',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Tono marfil elegante',
      activo: true,
    },

    // 3. FALTANTES / POR REPONER
    {
      nombreColor: 'Chocolate Oscuro',
      codigoHex: '#451A03',
      tipoMaterial: 'PLA',
      marca: 'eSUN',
      formato: 'CON_BOBINA',
      estadoStock: 'FALTANTE',
      porcentajeRestante: 0.0,
      stockBobinas: 0.0,
      stockGramos: 0,
      cantidadCompradaRef: 1,
      costoBobinaRef: 55.00,
      ubicacion: 'Por comprar (Digitalz)',
      temperaturaImpresion: '205-215°C',
      temperaturaCama: '60°C',
      estado: 'AGOTADO',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Requerido para pedidos de macetas y llaveros',
      activo: true,
    },
    {
      nombreColor: 'Ciruela',
      codigoHex: '#581C87',
      tipoMaterial: 'PLA',
      marca: 'eSUN',
      formato: 'CON_BOBINA',
      estadoStock: 'FALTANTE',
      porcentajeRestante: 0.0,
      stockBobinas: 0.0,
      stockGramos: 0,
      cantidadCompradaRef: 1,
      costoBobinaRef: 55.00,
      ubicacion: 'Por comprar (Digitalz)',
      temperaturaImpresion: '205-215°C',
      temperaturaCama: '60°C',
      estado: 'AGOTADO',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Color temático solicitado por clientes',
      activo: true,
    },
    {
      nombreColor: 'Marrón Oscuro',
      codigoHex: '#3E2723',
      tipoMaterial: 'PLA',
      marca: 'Creality',
      formato: 'CON_BOBINA',
      estadoStock: 'FALTANTE',
      porcentajeRestante: 0.0,
      stockBobinas: 0.0,
      stockGramos: 0,
      cantidadCompradaRef: 1,
      costoBobinaRef: 54.00,
      ubicacion: 'Por comprar (Digitalz)',
      temperaturaImpresion: '200-210°C',
      temperaturaCama: '55°C',
      estado: 'AGOTADO',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Para bases de dioramas',
      activo: true,
    },
    {
      nombreColor: 'Rojo Oscuro',
      codigoHex: '#7F1D1D',
      tipoMaterial: 'PLA',
      marca: 'eSUN',
      formato: 'CON_BOBINA',
      estadoStock: 'FALTANTE',
      porcentajeRestante: 0.0,
      stockBobinas: 0.0,
      stockGramos: 0,
      cantidadCompradaRef: 1,
      costoBobinaRef: 55.00,
      ubicacion: 'Por comprar (Digitalz)',
      temperaturaImpresion: '205-215°C',
      temperaturaCama: '60°C',
      estado: 'AGOTADO',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Tono vino / carmesí',
      activo: true,
    },
    {
      nombreColor: 'Terracota',
      codigoHex: '#A36F4C',
      tipoMaterial: 'PLA Matte',
      marca: 'eSUN Matte',
      formato: 'CON_BOBINA',
      estadoStock: 'FALTANTE',
      porcentajeRestante: 0.0,
      stockBobinas: 0.0,
      stockGramos: 0,
      cantidadCompradaRef: 1,
      costoBobinaRef: 58.00,
      ubicacion: 'Por comprar (Digitalz)',
      temperaturaImpresion: '205-215°C',
      temperaturaCama: '60°C',
      estado: 'AGOTADO',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Color insignia de la marca NOVA',
      activo: true,
    },
    {
      nombreColor: 'Verde Manzana',
      codigoHex: '#65A30D',
      tipoMaterial: 'PLA',
      marca: 'Sunlu',
      formato: 'CON_BOBINA',
      estadoStock: 'FALTANTE',
      porcentajeRestante: 0.0,
      stockBobinas: 0.0,
      stockGramos: 0,
      cantidadCompradaRef: 1,
      costoBobinaRef: 54.00,
      ubicacion: 'Por comprar (Digitalz)',
      temperaturaImpresion: '200-210°C',
      temperaturaCama: '55°C',
      estado: 'AGOTADO',
      alertaCritica: false,
      notaProduccion: null,
      notas: 'Verde brillante',
      activo: true,
    },
    {
      nombreColor: 'Verde Oscuro',
      codigoHex: '#14532D',
      tipoMaterial: 'PLA',
      marca: 'Creality',
      formato: 'CON_BOBINA',
      estadoStock: 'FALTANTE',
      porcentajeRestante: 0.0,
      stockBobinas: 0.0,
      stockGramos: 0,
      cantidadCompradaRef: 1,
      costoBobinaRef: 55.00,
      ubicacion: 'Por comprar urgente',
      temperaturaImpresion: '200-210°C',
      temperaturaCama: '55°C',
      estado: 'AGOTADO',
      alertaCritica: true,
      notaProduccion: 'Supongo que no alcanza para otro pedido',
      notas: 'Alerta crítica de stock en taller',
      activo: true,
    },
    {
      nombreColor: 'Azul Oscuro',
      codigoHex: '#1E3A8A',
      tipoMaterial: 'PLA',
      marca: 'Creality',
      formato: 'CON_BOBINA',
      estadoStock: 'FALTANTE',
      porcentajeRestante: 0.0,
      stockBobinas: 0.0,
      stockGramos: 0,
      cantidadCompradaRef: 1,
      costoBobinaRef: 54.00,
      ubicacion: 'Por comprar urgente',
      temperaturaImpresion: '200-210°C',
      temperaturaCama: '55°C',
      estado: 'AGOTADO',
      alertaCritica: true,
      notaProduccion: 'Supongo que no alcanza para otro pedido',
      notas: 'Alerta crítica de stock en taller',
      activo: true,
    }
  ]

  for (const f of filamentos) {
    await prisma.inventarioFilamento.create({ data: f })
  }

  const consumibles = [
    {
      nombre: 'Lápices Acrílicos',
      categoria: 'POSTPROCESADO',
      estado: 'DISPONIBLE',
      cantidad: '1 set (12 colores)',
      notas: 'Para retoque y pintura fina de detalles en figuras impresas',
    },
    {
      nombre: 'Pegamento (Cianoacrilato)',
      categoria: 'ADHESION',
      estado: 'DISPONIBLE',
      cantidad: '2 frascos con aplicador',
      notas: 'Fijación ultra rápida de partes y ensambles 3D',
    },
    {
      nombre: 'Mascarilla con Filtro y Lentes',
      categoria: 'SEGURIDAD',
      estado: 'DISPONIBLE',
      cantidad: '1 kit EPP completo',
      notas: 'Protección personal obligatoria para lijado y postprocesado con químicos',
    },
    {
      nombre: 'Yeso / Masilla para emparejar piezas',
      categoria: 'POSTPROCESADO',
      estado: 'BAJO_STOCK',
      cantidad: '1 pote (~30% restante)',
      notas: 'Relleno de líneas de capa y suavizado de superficies',
    },
    {
      nombre: 'Sellante en Aerosol',
      categoria: 'POSTPROCESADO',
      estado: 'DISPONIBLE',
      cantidad: '1 lata (Acabado Mate)',
      notas: 'Capa protectora final contra rayos UV y humedad',
    },
  ]

  for (const c of consumibles) {
    await prisma.consumibleTaller.create({ data: c })
  }

  console.log('--- SEEDING COMPLETED SUCCESSFULLY ---')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
